// Auto-generated by generate_strip_js.py
window.SELFE_STRIP_DATA = {
  "2": [
    {
      "src": "strip/2/000001.png",
      "prompt": "A cat sculpted from folded paper, origami creases and fibers visible, sunlight shining through edges, photoreal delicate realism."
    },
    {
      "src": "strip/2/000002.png",
      "prompt": "A couch made entirely of bubble wrap, soft reflections on plastic surface, diffused studio light, photoreal playful realism."
    },
    {
      "src": "strip/2/000003.png",
      "prompt": "A cat entirely composed of mosaic tiles, reflections shifting as light changes, soft shadow detail, photoreal artistic surrealism."
    },
    {
      "src": "strip/2/000004.png",
      "prompt": "A house constructed from luminous jelly bricks glowing at night, detailed transparency and refraction, cinematic realism."
    },
    {
      "src": "strip/2/000005.png",
      "prompt": "A cinematic night street in the rain, film grain aesthetic, blurred reflections on wet pavement, bokeh lights glowing softly, moody tones, photoreal but painterly texture."
    },
    {
      "src": "strip/2/000006.png",
      "prompt": "A dog portrait after rain, visible wet fur granularity, water droplets on nose, natural sunlight reflections, photoreal clarity."
    },
    {
      "src": "strip/2/000007.png",
      "prompt": "Portrait of a wolf under snowfall, frost collecting on muzzle and fur, visible texture and natural grain, calm expression, photoreal cold environment realism."
    },
    {
      "src": "strip/2/000008.png",
      "prompt": "Portrait of a red fox with wet fur, golden-hour light reflecting off individual hairs, fine grain visible but natural, detailed eyes and whiskers, cinematic wildlife realism."
    },
    {
      "src": "strip/2/000009.png",
      "prompt": "Close-up portrait of a snow leopard, fur glistening with ice crystals, visible granular texture on whiskers and face, cold blue background, photoreal natural detail."
    },
    {
      "src": "strip/2/000010.png",
      "prompt": "A lion standing atop a rock during a lightning storm, raindrops visible, wet fur reflecting flashes, photoreal dramatic realism."
    },
    {
      "src": "strip/2/000011.png",
      "prompt": "A coastal lighthouse painted in oil, waves crashing beneath, visible brush texture in sky and foam, dramatic lighting, expressive realism."
    },
    {
      "src": "strip/2/000012.png",
      "prompt": "An oil painting of a woman with her hair turning into waves, seascape blending with portrait, tactile brushwork, painterly surreal tone."
    },
    {
      "src": "strip/2/000013.png",
      "prompt": "A large oil painting of a tree whose roots form a sleeping human face, dawn light emerging through leaves, allegorical ecological symbolism, painterly tone."
    },
    {
      "src": "strip/2/000014.png",
      "prompt": "An oil painting of a woman standing under rain of flowers, soft pastel palette, impressionist texture, symbolic representation of renewal and healing."
    },
    {
      "src": "strip/2/000015.png",
      "prompt": "A close-up pencil portrait of a cat, fine fur texture drawn with short strokes, sharp reflective eyes, soft blurred shading around edges, traditional sketch style."
    },
    {
      "src": "strip/2/000016.png",
      "prompt": "A pencil sketch of a fox sitting quietly on a rock, fine graphite shading on fur, soft smudged background trees, delicate cross-hatching, realistic hand-drawn tone."
    },
    {
      "src": "strip/2/000017.png",
      "prompt": "A glowing figure walking through dense fog forest, faint light radiating from body, ethereal surreal tone."
    },
    {
      "src": "strip/2/000018.png",
      "prompt": "A white deer standing in a fog-covered meadow, antlers glowing faintly, mist swirling around legs, dreamlike fantasy realism."
    },
    {
      "src": "strip/2/000019.png",
      "prompt": "The word “Self-E” appearing faintly through condensation on train window, blurred landscape passing behind, city lights refracting, cinematic melancholic tone."
    }
  ],
  "4": [
    {
      "src": "strip/4/000001.png",
      "prompt": "A folded wool sweater on armchair near window, golden light passing through fabric fibers, plant shadow cast across surface, cinematic homely tone."
    },
    {
      "src": "strip/4/000002.png",
      "prompt": "A cat composed of smoke sitting on rooftop, its form dissolving into night air, glowing eyes reflecting city lights, detailed cinematic surrealism."
    },
    {
      "src": "strip/4/000003.png",
      "prompt": "A mountain range shaped like sleeping giant’s face, forests growing on slopes, sunlight outlining features, atmospheric cinematic realism."
    },
    {
      "src": "strip/4/000004.png",
      "prompt": "A volcano erupting with petals instead of lava, clouds of color drifting across sky, surreal cinematic beauty."
    },
    {
      "src": "strip/4/000005.png",
      "prompt": "A pair of scissors lying beside thread spools on sewing table, cloth folded nearby, amber light glowing from side lamp, cinematic handmade warmth."
    },
    {
      "src": "strip/4/000006.png",
      "prompt": "A ceramic bowl with almonds and dried figs, sunlight from side window illuminating texture, woven mat beneath glowing golden, photoreal cozy realism."
    },
    {
      "src": "strip/4/000007.png",
      "prompt": "A wooden violin resting on linen cloth, sunlight filtering through curtains creating stripes of gold across body, fine strings catching warm highlights, dust visible in soft air, photoreal atmosphere."
    },
    {
      "src": "strip/4/000008.png",
      "prompt": "A jar of jam beside slice of bread on plate, butter knife reflecting morning light, crumbs on wooden table, warm breakfast tone, photoreal detailed realism."
    },
    {
      "src": "strip/4/000009.png",
      "prompt": "A wicker basket filled with fresh oranges, sunlight creating intricate shadows through weave, tablecloth glowing warm white, photoreal rustic realism."
    },
    {
      "src": "strip/4/000010.png",
      "prompt": "A loaf of bread sliced open on wooden board, steam rising faintly, crumbs scattered, sunlight cutting across table, warm rustic kitchen realism."
    },
    {
      "src": "strip/4/000011.png",
      "prompt": "A vintage camera resting beside cup of tea, window light golden and soft, reflections glinting off lens, faint steam drifting between objects, photoreal cozy composition."
    },
    {
      "src": "strip/4/000012.png",
      "prompt": "A stack of pancakes drizzled with syrup, sunlight shimmering on surface, steam rising, golden tones filling composition, photoreal breakfast warmth."
    },
    {
      "src": "strip/4/000013.png",
      "prompt": "A wine glass half-filled with red liquid placed on marble surface, candlelight reflecting through curved glass, golden hue filling background, photoreal still-life warmth."
    },
    {
      "src": "strip/4/000014.png",
      "prompt": "A ceramic cat figurine sitting beside potted plant on windowsill, light catching edges, warm shadow pattern across wall, photoreal still-life realism."
    },
    {
      "src": "strip/4/000015.png",
      "prompt": "A ceramic incense holder with smoke spiraling upward, candle behind casting warm glow, wooden texture detailed beneath, photoreal cinematic still-life."
    },
    {
      "src": "strip/4/000016.png",
      "prompt": "photo-realistic, natural lighting, fine texture, high dynamic range. A parrot painted entirely as graffiti strokes, neon spray textures forming feathers, perched on a brick wall covered in tags, urban street-art style."
    },
    {
      "src": "strip/4/000017.png",
      "prompt": "photo-realistic, natural lighting, fine texture, high dynamic range. A panda made of stitched denim patches with visible seams, sitting on a pile of colorful fabric rolls in a fashion studio, editorial look."
    },
    {
      "src": "strip/4/000018.png",
      "prompt": "A plate of pastries beside teacup, sunlight highlighting golden crusts, powdered sugar shimmering under warm glow, photoreal comforting realism."
    },
    {
      "src": "strip/4/000019.png",
      "prompt": "A horse composed of flowing ink brush strokes, tail dissolving into calligraphy, galloping across rice-paper landscape, sumi-e painting style."
    },
    {
      "src": "strip/4/000020.png",
      "prompt": "A frog whose skin is polished marble with subtle veining, sitting on stone pedestal in museum hall, dramatic spotlights, gallery realism."
    },
    {
      "src": "strip/4/000021.png",
      "prompt": "A goat rendered as low-poly 3D geometry, faceted surfaces with pastel gradients, standing in stylized polygonal mountains, minimalist game-art style."
    }
  ],
  "8": [
    {
      "src": "strip/8/000001.png",
      "prompt": "A fox mage standing in misty forest, staff glowing faintly, fur and fabric detail visible, backlight through fog, photoreal cinematic realism."
    },
    {
      "src": "strip/8/000002.png",
      "prompt": "An underwater cathedral built from bioluminescent jellyfish and coral spires; stained-glass light beams, divers as tiny silhouettes, long-exposure feel, drifting plankton bokeh, deep teal palette, ethereal, tranquil, meticulously detailed marine textures."
    },
    {
      "src": "strip/8/000003.png",
      "prompt": "A coastal tide pool macro; anemone tentacles, starfish texture, wet sand grains, polarized glare control, vibrant but natural color, scientific clarity, intimate."
    },
    {
      "src": "strip/8/000004.png",
      "prompt": "A snow leopard on a rocky ledge; fine fur detail, icy breath, mountain wind, distant glacier, long lens compression, regal stillness, natural documentary tone."
    },
    {
      "src": "strip/8/000005.png",
      "prompt": "A woman in an op art outfit is sitting in front of a mid-century decor interior, her melancholic self-portrait captured in a close-up light leak macro photograph. Her eyes, half-closed, are surrounded by the black shade of light and the Venetian blind shadow effect. The striped pattern of the suprematist art style subtly reflects on her face as she gazes introspectively, underscoring the emotional depth of the photograph."
    },
    {
      "src": "strip/8/000006.png",
      "prompt": "Side-profile portrait of a desert nomad woman with golden sand dust on skin, windblown hair, reflected sunset light, detailed texture and warm tones, 135mm lens, photoreal."
    },
    {
      "src": "strip/8/000007.png",
      "prompt": "Portrait of a jungle guardian with vine tattoos and green-gold war paint, wet skin glistening under filtered sunlight, 85mm, macro detail on skin texture, cinematic naturalism."
    },
    {
      "src": "strip/8/000008.png",
      "prompt": "Medium close-up portrait of a man with storm-weathered face, raindrops on beard and eyelashes, harsh light through fog, rugged photorealism, 135mm telephoto portrait."
    },
    {
      "src": "strip/8/000009.png",
      "prompt": "Portrait of a desert warrior painted in ochre and charcoal, golden sunset rim light, grainy sand in air, detailed facial paint texture, shallow DOF, 100mm editorial realism."
    },
    {
      "src": "strip/8/000010.png",
      "prompt": "A cozy breakfast setup on a white table: croissants, a cup of cappuccino, and a small vase with wildflowers; sunlight streaming through a window, shallow depth of field, photoreal realism."
    },
    {
      "src": "strip/8/000011.png",
      "prompt": "A crystal wolf standing on icy ground, refracted light through body, cool cyan color palette, cinematic fantasy realism."
    },
    {
      "src": "strip/8/000012.png",
      "prompt": "A glowing jellyfish swarm under the sea, each translucent body showing electric pink and cyan veins, soft particle haze, photoreal aquatic color palette."
    },
    {
      "src": "strip/8/000013.png",
      "prompt": "A cozy cottage built entirely from red and white yarn; knitted walls, woven roof shingles, soft texture visible in each thread, golden sunlight casting gentle shadows, photoreal tactile realism."
    },
    {
      "src": "strip/8/000014.png",
      "prompt": "A teddy bear knitted from steel wire, interwoven strands glinting under soft light, realistic reflections, photoreal tactile surrealism."
    },
    {
      "src": "strip/8/000015.png",
      "prompt": "A pair of running shoes made from woven leaves, veins visible, dew on edges, forest ground background, photoreal natural craftsmanship."
    },
    {
      "src": "strip/8/000016.png",
      "prompt": "A boat made of glowing jellyfish membranes, translucent hull floating on dark water, bioluminescent reflections, photoreal aquatic surrealism."
    },
    {
      "src": "strip/8/000017.png",
      "prompt": "A robot built from wood and moss, bark texture mixed with metallic joints, glowing eyes, photoreal fantasy craftsmanship."
    },
    {
      "src": "strip/8/000018.png",
      "prompt": "A castle made of coral and seashells rising from ocean waves, sunlight glinting off textures, photoreal aquatic fantasy."
    },
    {
      "src": "strip/8/000019.png",
      "prompt": "A bison standing in foggy grassland at dawn, dew on tall grass, sun barely visible through haze, fur glistening with moisture, cinematic atmospheric realism."
    },
    {
      "src": "strip/8/000020.png",
      "prompt": "A shallow reef under midday sun; dappled caustics, suspended particulates; a clownfish gently kissing the word “SELFE” spelled in crisp bubble letters; case-sensitive “SELFE”, clear and correctly spelled; clean baseline and spacing, high legibility, photoreal, 50mm underwater perspective."
    },
    {
      "src": "strip/8/000021.png",
      "prompt": "Close-up of a mechanical hummingbird with glass wings; reflections and engraved filigree, glowing core visible inside chest, photoreal macro style."
    }
  ],
  "50": [
    {
      "src": "strip/50/000001.png",
      "prompt": "cinematic, film still, dramatic lighting, shallow depth of field, 35mm. A dragon-blooded beast encased in ornate jade-inlaid armor, wind-torn silk banners trailing from pauldrons, roars atop jungle ziggurat; storm clouds, lightning, dense foliage and distant fires complete a war-torn horizon."
    },
    {
      "src": "strip/50/000002.png",
      "prompt": "A ceramic coffee cup with a subtle geometric pattern on a worn wooden café table, street-facing window behind showing rainy cobblestones, pedestrians with umbrellas, parked bicycles, and glowing shop signs at dusk."
    },
    {
      "src": "strip/50/000003.png",
      "prompt": "A silk dress printed with blurred landscapes on a dress form, fashion atelier behind lined with cutting tables, mood boards, open sketchbooks, and racks of unfinished garments and threads."
    },
    {
      "src": "strip/50/000004.png",
      "prompt": "A valley full of blooming lupines and daisies, 16:9 panoramic view, rolling hills leading toward mountain horizon, warm afternoon light highlighting color contrast, photoreal cinematic realism."
    },
    {
      "src": "strip/50/000005.png",
      "prompt": "A crystal-clear river winding through alpine valley, rocks visible under water, pine forest on both sides, snow mountains on horizon, clouds mirrored in river, natural photoreal panoramic 16:9 scene."
    },
    {
      "src": "strip/50/000006.png",
      "prompt": "A woolen cottage with soft fabric walls standing at edge of snowy forest, fibers catching frost, smoke rising from knitted chimney, soft golden sunrise light, photoreal 16:9 dreamlike realism."
    },
    {
      "src": "strip/50/000007.png",
      "prompt": "A rabbit made of transparent glass jumping across a shallow creek, sunlight refracting rainbow light through its body, ripples and stones visible beneath, forest on both sides, 16:9 photoreal wide scene."
    },
    {
      "src": "strip/50/000008.png",
      "prompt": "A mechanical owl flying through foggy canyon, metal feathers reflecting sunlight, cliffs on both sides detailed, waterfalls cascading below, 16:9 epic cinematic realism."
    },
    {
      "src": "strip/50/000009.png",
      "prompt": "A woman’s face half underwater, one half reflecting natural skin detail, freckles and hair strands visible, the other refracted through the water surface into blurred abstract ripples, bubbles and sunlight caustics around, dreamy cinematic realism."
    },
    {
      "src": "strip/50/000010.png",
      "prompt": "A human eye where the iris is a spinning galaxy, starlight reflecting on eyelashes, ethereal cosmic realism."
    },
    {
      "src": "strip/50/000011.png",
      "prompt": "A human face emerging from cracked porcelain, half side smooth and half crumbled revealing crystalline interior, emotional surreal realism."
    },
    {
      "src": "strip/50/000012.png",
      "prompt": "A lush forest clearing after rain, wide landscape, puddles reflecting tall pines, moss-covered stones and ferns in the background, mist hanging between trunks, sunlight streaming diagonally through branches, vivid sharp focus across entire frame, 16:9 natural realism."
    },
    {
      "src": "strip/50/000013.png",
      "prompt": "cinematic, film still, dramatic lighting, shallow depth of field, 35mm. A traveler in layered linen tunic and leather chest harness, decorated scarf wrapped around neck, multiple charm bracelets on wrists, wading through shallow jungle river, vine-covered ruins and broken statues behind, bright sunlight cutting through canopy gaps."
    }
  ]
};
